window.lesson3 = {
    id: 3,
    title: 'Lektion 3 \u2013 Eigenschaften Gottes (2)',
    description: '23 Vokabeln, 6 \u00dcbungen',
    vocabulary: [
        { arabic: '\u0622\u062e\u0631\u0629', german: 'Jenseits / die Letzte', distractors: ['Diesseits', 'Erde', 'Himmel'] },
        { arabic: '\u062c\u064e\u0645\u0650\u064a\u0639\u0627\u064b', german: 'alle / allesamt', distractors: ['einige', 'viele', 'wenige'] },
        { arabic: '\u062f\u0650\u064a\u0652\u0646', german: 'Vergeltung / Religion', distractors: ['Weg', 'Herrschaft', 'Urteil'] },
        { arabic: '\u0635\u0650\u0631\u064e\u0627\u0637', german: 'Weg / Pfad', distractors: ['Herrschaft', 'Zeichen', 'Sch\u00f6pfung'] },
        { arabic: '\u0642\u064e\u0628\u0652\u0644', german: 'vor / bevor', distractors: ['nach', 'w\u00e4hrend', 'mit'] },
        { arabic: '\u0645\u064e\u0627\u0644\u0650\u0643', german: 'Besitzer / Herr', distractors: ['Diener', 'Gesandter', 'Sch\u00f6pfer'] },
        { arabic: '\u0645\u064f\u0633\u0652\u062a\u064e\u0642\u0650\u064a\u0652\u0645', german: 'gerade / aufrecht', distractors: ['krumm', 'breit', 'kurz'] },
        { arabic: '\u0648\u064e\u0627\u062d\u0650\u062f', german: 'eine (fem. und mask.)', distractors: ['zwei', 'alle', 'keine'] },
        { arabic: '\u064a\u064e\u0648\u0652\u0645', german: 'Tag', distractors: ['Nacht', 'Morgen', 'Abend'] },
        { arabic: '\u0647\u064e\u0630\u064e\u0627', german: 'dieser / diese', distractors: ['jener', 'jene', 'welcher'] },
        { arabic: '\u064a\u0650', german: '(Endung) mein/e', distractors: ['dein/e', 'unser/e', 'euer/e'] },
        { arabic: '\u064a\u064e\u0627 \u0623\u064e\u064a\u0651\u064f\u0647\u064e\u0627', german: 'Oh / O ihr, die', distractors: ['aber', 'gewiss', 'damit'] },
        { arabic: '\u064a\u064e\u0634\u064e\u0627\u0621\u064f', german: 'er will / m\u00f6chte', distractors: ['er geht', 'er sieht', 'er spricht'] },
        { arabic: '\u064a\u064e\u0647\u0652\u062f\u0650\u064a', german: 'er leitet recht', distractors: ['er erschuf', 'er richtet', 'er sendet'] },
        { arabic: '\u0627\u0639\u0652\u0628\u064f\u062f\u064f\u0648\u0627', german: 'dient / betet an (Befehlsform)', distractors: ['ihr dient', 'er dient', 'sie beten an'] },
        { arabic: '\u0627\u0644\u0651\u064e\u0630\u0650\u064a', german: 'der / derjenige, der', distractors: ['die / diejenigen, die', 'wer / wer auch immer', 'dieser / diese'] },
        { arabic: '\u0627\u0644\u0651\u064e\u0630\u0650\u064a\u0652\u0646\u064e', german: 'die / diejenigen, die', distractors: ['der / derjenige, der', 'wer / wer auch immer', 'dieser / diese'] },
        { arabic: '\u0625\u0650\u0644\u064e\u0649', german: 'zu / bis', distractors: ['von', 'in', 'mit'] },
        { arabic: '\u0627\u0644\u0652\u0623\u064f\u0648\u0652\u0644\u064e\u0649', german: 'Diesseits / die Erste', distractors: ['Jenseits', 'Himmel', 'Erde'] },
        { arabic: '\u062d\u064f\u0643\u0652\u0645', german: 'Herrschaft / Urteil', distractors: ['Religion', 'Weg', 'Zeichen'] },
        { arabic: '\u0645\u064f\u0644\u0652\u0643', german: 'Herrschaft / K\u00f6nigreich', distractors: ['Besitz', 'Land', 'Haus'] },
        { arabic: '\u0645\u064e\u0646\u0652', german: 'wer / wer auch immer', distractors: ['was', 'wo', 'wann'] },
        { arabic: '\u0648\u064e\u0644\u0650\u064a', german: 'Besch\u00fctzer / Vormund', distractors: ['Feind', 'Diener', 'Gesandter'] }
    ],
    grammarNote: {
        title: 'Eigenschaften Gottes (2)',
        text: 'Wir wissen, dass kein existierendes Wesen die F\u00e4higkeit und W\u00fcrdigkeit besitzt, die Welt zu verwalten und \u00fcber sie zu herrschen, au\u00dfer Gott; daher kann man den Befehl keines anderen als Gottes annehmen, und nur Er ist es, Der angebetet werden muss: \u0648\u064e\u0625\u0650\u0644\u064e\u0647\u064f\u0643\u064f\u0645\u0652 \u0625\u0650\u0644\u064e\u0647\u064c \u0648\u064e\u0627\u062d\u0650\u062f\u064c \u0644\u0651\u064e\u0627 \u0625\u0650\u0644\u064e\u0647\u064e \u0625\u0650\u0644\u0651\u064e\u0627 \u0647\u064f\u0648\u064e. Die Herrschaft \u00fcber die Himmel und die Erde liegt in Seiner Hand: \u0648\u064e\u0644\u0650\u0644\u0651\u064e\u0647\u0650 \u0645\u064f\u0644\u0652\u0643\u064f \u0627\u0644\u0633\u0651\u064e\u0645\u064e\u0627\u0648\u064e\u0627\u062a\u0650 \u0648\u064e\u0627\u0644\u0652\u0623\u064e\u0631\u0652\u0636\u0650. Als Gott die Gesch\u00f6pfe erschuf, \u00fcbernahm Er auch die Herrschaft und Leitung ihrer Angelegenheiten: \u0625\u0650\u0646\u0651\u064e \u0627\u0644\u0644\u0651\u064e\u0647\u064e \u0631\u064e\u0628\u0651\u0650\u064a \u0648\u064e\u0631\u064e\u0628\u0651\u064f\u0643\u064f\u0645\u0652 \u0641\u064e\u0627\u0639\u0652\u0628\u064f\u062f\u064f\u0648\u0647\u064f. Wenn wir uns den g\u00f6ttlichen Befehlen unterwerfen, nimmt Er uns unter den Schatten Seiner besonderen Vormundschaft: \u0648\u064e\u0627\u0644\u0644\u0651\u064e\u0647\u064f \u0648\u064e\u0644\u0650\u064a\u0651\u064f \u0627\u0644\u0652\u0645\u064f\u0624\u0652\u0645\u0650\u0646\u0650\u064a\u0652\u0646\u064e.'
    },
    exercises: {
        matching: {
            pairs: [
                { arabic: 'مَالِكِ يَوْمِ ٱلدَّينِ', german: 'Besitzer des Tages der Vergeltung / Religion.' },
                { arabic: 'ٱهْدِنَا ٱلصِّرَاطَ ٱلْمُسْتَقِيمَ', german: 'Der gerade Weg / Pfad.' },
                { arabic: 'يَٰٓأَيُّهَا ٱلنَّاسُ ٱعْبُدُوا۟ رَبَّكُمُ', german: 'O ihr Menschen, dient eurem Herrn!' },
                { arabic: 'وَإِلٰهُكُمْ إِلٰهٌ وَٰحِدٌ', german: 'Und euer Anbetungswürdiger ist ein einziger Anbetungswürdiger.' },
                { arabic: 'لَّا إِلَٰهَ إِلَّا هُوَ', german: 'Es gibt keinen Gott außer Ihm.' },
                { arabic: 'وَٱللَّهُ يَهْدِي مَن يَشَآءُ إِلَىٰ صِرَاطٍ مُّسْتَقِيمٍ', german: 'Und Allah leitet recht, wen Er will, zu einem geraden Weg.' },
                { arabic: 'ٱلَّذِي خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ', german: 'Derjenige, der die Himmel und die Erde erschuf.' },
                { arabic: 'لَهُ مُلْكُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ', german: 'Ihm gehört die Herrschaft der Himmel und der Erde.' },
                { arabic: 'وَٱللَّهُ وَلِيُّ ٱلْمُؤْمِنِينَ', german: 'Und Allah ist der Beschützer der Gläubigen.' },
                { arabic: 'إِنَّ ٱللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ', german: 'Gewiss, Allah ist über jede Sache allmächtig.' },
                { arabic: 'وَهُوَ ٱلَّذِي خَلَقَكُم', german: 'Und Er ist derjenige, der euch erschuf.' },
                { arabic: 'مَن قَبْلِكُمْ', german: 'Wer vor euch (war) / Von vor euch.' },
                { arabic: 'فِي ٱلدُّنْيَا وَٱلْآخِرَةِ', german: 'Im Diesseits und im Jenseits.' },
                { arabic: 'هٰذَا صِرَاطٌ مُّسْتَقِيمٌ', german: 'Dies ist ein gerader Weg.' }
            ]
        },
        translatePhrases: [
            { arabic: 'يَٰٓأَيُّهَا ٱلنَّاسُ ٱعْبُدُوا۟ رَبَّكُمُ ٱلَّذِي خَلَقَكُمْ', options: ['O ihr Menschen, dient eurem Herrn, Der euch erschuf.', 'O ihr Menschen, dient Allah, Der euch erschuf.', 'O ihr Menschen, Er hat euch erschaffen, dient eurem Schöpfer.'], correct: 0 },
            { arabic: 'وَإِلٰهُكُمْ إِلٰهٌ وَٰحِدٌ لَّا إِلَٰهَ إِلَّا هُوَ', options: ['Und euer Anbetungswürdiger ist niemand außer Allah; es gibt keinen Gott außer Ihm.', 'Und euer Anbetungswürdiger ist ein einziger Anbetungswürdiger; es gibt keinen Gott außer Ihm.', 'Und euer Allah ist der einzige Anbetungswürdige; es gibt keinen Gott außer Ihm.'], correct: 1 },
            { arabic: 'وَٱللَّهُ يَهْدِي مَن يَشَآءُ إِلَىٰ صِرَاطٍ مُّسْتَقِيمٍ', options: ['Gewiss, Allah kennt wen Er will, den Weg aller Menschen auf der Erde.', 'Und Allah leitet recht, wen Er will, auf jedem Weg.', 'Und Allah leitet recht, wen Er will, zu einem geraden Weg.'], correct: 2 },
            { arabic: 'ٱلَّذِي خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ جَمِيعًا', options: ['Derjenige, Der die Himmel und die Erde allesamt erschuf.', 'Allah, Der die Himmel und die Erde allesamt erschuf.', 'Derjenige, Der den Mond, die Sonne und die Planeten allesamt erschuf.'], correct: 0 },
            { arabic: 'وَٱللَّهُ وَلِيُّ ٱلَّذِينَ', options: ['Und Allah ist der Schöpfer derjenigen, die...', 'Und Allah ist der Beschützer derjenigen, die...', 'Und Allah ist der Mächtige derjenigen, die...'], correct: 1 },
            { arabic: 'مَالِكِ يَوْمِ ٱلدَّينِ', options: ['Allah ist der Besitzer des Tages der Vergeltung / Religion.', 'Herr des Tages der Vergeltung / Religion.', 'Besitzer des Tages der Vergeltung / Religion.'], correct: 2 },
            { arabic: 'هٰذَا صِرَاطٌ مُّسْتَقِيمٌ', options: ['Dies ist ein gerader Weg.', 'Ist dies ist ein gerader Weg Allahs?', 'Dies ist Allahs gerader Weg'], correct: 0 },
            { arabic: 'فِي ٱلْأُولَىٰ وَٱلْآخِرَةِ', options: ['In den Himmeln und auf der Erde.', 'Im Diesseits und im Jenseits.', 'Bei Allah ist das Diesseits und das Jenseits.'], correct: 1 },
            { arabic: 'لَّهُ مُلْكُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ', options: ['Ihm gehört die Herrschaft der Sonne und des Mondes.', 'Allah gehört die Herrschaft der Himmel und der Erde.', 'Ihm gehört die Herrschaft der Himmel und der Erde.'], correct: 2 },
            { arabic: 'وَكَانَ ٱللَّهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيرًا', options: ['Und Allah ist der Allsehende über die Nacht und den Tag.', 'Und Allah ist der Herrscher im Diesseits und Jenseits über jede Sache.', 'Und Allah ist über jede Sache allmächtig.'], correct: 2 },
            { arabic: 'إِنَّ ٱللَّهَ هُوَ ٱلْحَيُّ ٱلْقَيُّومُ', options: ['Gewiss, Allah, Er ist der Lebendige, der Beständige.', 'Ist Allah der Lebendige, der Beständige?', 'Gewiss, Allah ist Er, der Lebendige, der Weise.'], correct: 0 },
            { arabic: 'وَٱللَّهُ سَمِيعٌ عَلِيمٌ', options: ['Und Allah erschuf die Sprachen und Farben.', 'Und Allah ist allhörend, allwissend.', 'Und Allah ist der Mächtige, der Weise.'], correct: 1 },
            { arabic: 'مَنْ خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ', options: ['Welches Zeichen ist in den Himmeln und auf der Erde?', 'Wer außer erschuf die Himmel und die Erde?', 'Wer erschuf die Himmel und die Erde?'], correct: 2 },
            { arabic: 'وَمَن قَبْلِكُمْ', options: ['Und wer nach euch erschaffen wird.', 'Und wer vor euch (war).', 'Und wer von den Gläubigen vor euch (war).'], correct: 1 },
            { arabic: 'رَبُّ كُلِّ شَيْءٍ', options: ['Herr jeder Sache.', 'Herr des Lichts und des Tages.', 'Schöpfer jeder Sache.'], correct: 0 },
            { arabic: 'إِنَّ فِي ذَٰلِكَ لَآيَةً لِّلْمُؤْمِنِينَ', options: ['Wahrlich, darin sind Zeichen für die Gläubigen.', 'Gewiss, darin ist wahrlich ein Zeichen für die Gläubigen.', 'Gewiss, darin ist wahrlich ein Zeichen für diejenigen, die glauben.'], correct: 1 },
            { arabic: 'وَهُوَ ٱلْعَزِيزُ ٱلْحَكِيمُ', options: ['Und Er ist der Erhabene, der Barmherzige.', 'Und Er ist der Mächtige, der Weise.', 'Und Er ist der Allhörende, der Allsehende.'], correct: 1 }
        ],
        phraseOrder: [
            { arabic: 'يَٰٓأَيُّهَا ٱلنَّاسُ ٱعْبُدُوا۟ رَبَّكُمُ', words: ['O ihr', 'Menschen', 'dient', 'eurem', 'Herrn'] },
            { arabic: 'وَإِلٰهُكُمْ إِلٰهٌ وَٰحِدٌ', words: ['Und', 'euer', 'Anbetungswürdiger', 'ist ein einziger', 'Anbetungswürdiger'] },
            { arabic: 'وَٱللَّهُ يَهْدِي مَن يَشَآءُ إِلَىٰ صِرَاطٍ مُّسْتَقِيمٍ', words: ['Und', 'Allah', 'leitet recht', 'wen', 'Er will', 'zu einem', 'geraden', 'Weg'] },
            { arabic: 'ٱلَّذِي خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ', words: ['Derjenige, der', 'die Himmel', 'und', 'die Erde', 'erschuf'] },
            { arabic: 'لَهُ مُلْكُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ', words: ['Ihm gehört', 'die Herrschaft', 'der Himmel', 'und', 'der Erde'] },
            { arabic: 'مَالِكِ يَوْمِ ٱلدَّينِ', words: ['Besitzer', 'des Tages', 'der Vergeltung'] },
            { arabic: 'وَٱللَّهُ وَلِيُّ ٱلْمُؤْمِنِينَ', words: ['Und', 'Allah', 'ist der Beschützer', 'der Gläubigen'] },
            { arabic: 'هٰذَا صِرَاطٌ مُّسْتَقِيمٌ', words: ['Dies ist', 'ein gerader', 'Weg'] },
            { arabic: 'فِي ٱلْأُولَىٰ وَٱلْآخِرَةِ', words: ['Im', 'Diesseits', 'und', 'im Jenseits'] },
            { arabic: 'لَهُ ٱلْحُكْمُ', words: ['Ihm', 'gehört', 'das Urteil'] },
            { arabic: 'مَن قَبْلِكُمْ', words: ['Wer', 'vor', 'euch', '(war)'] },
            { arabic: 'إِنَّ ٱللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ', words: ['Gewiss', 'Allah', 'ist', 'über', 'jede', 'Sache', 'allmächtig'] },
            { arabic: 'وَهُوَ ٱلَّذِي خَلَقَكُم', words: ['Und', 'Er', 'ist derjenige', 'der', 'euch', 'erschuf'] },
            { arabic: 'وَإِلَىٰ ٱللَّهِ', words: ['Und', 'zu', 'Allah'] },
            { arabic: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَالَمِينَ', words: ['Das Lob', 'gehört', 'Allah', 'dem Herrn', 'der Welten'] }
        ],
        fillBlank: [
            { arabic: 'يَٰٓأَيُّهَا ٱلنَّاسُ \u00a6 رَبَّكُمُ', hint: 'O ihr Menschen, dient eurem Herrn!', options: ['يَهْدِي', 'ٱعْبُدُوا۟', 'يَتَفَكَّرُونَ'], correct: 1 },
            { arabic: 'وَٱللَّهُ يَهْدِي مَن يَشَآءُ إِلَىٰ صِرَاطٍ \u00a6', hint: 'Und Allah leitet recht, wen er will zu einem geraden Weg', options: ['مُّسْتَقِيمٍ', 'عَالَمِينَ', 'أُولَىٰ'], correct: 0 },
            { arabic: 'مَالِكِ يَوْمِ \u00a6', hint: 'Besitzer des Tages der Vergeltung / Religion', options: ['ٱلْحُكْمِ', 'ٱلدَّينِ', 'ٱلْمُلْكِ'], correct: 1 },
            { arabic: 'وَٱللَّهُ \u00a6 ٱلْمُؤْمِنِينَ', hint: 'Und Allah ist der Beschützer der Gläubigen', options: ['إِلٰهَ', 'مَالِكُ', 'وَلِيُّ'], correct: 2 },
            { arabic: 'ٱلَّذِي خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ \u00a6', hint: '... derjenige, der erschuf die Himmel und die Erde allesamt', options: ['جَمِيعًا', 'وَاحِدَةً', 'آيَةً'], correct: 0 },
            { arabic: '\u00a6 صِرَاطٌ مُّسْتَقِيمٌ', hint: 'Dies ist ein gerader Weg', options: ['ذَٰلِكَ', 'هٰذَا', 'ٱلَّذِي'], correct: 1 },
            { arabic: 'لَهُ \u00a6 ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ', hint: 'Ihm gehört die Herrschaft der Himmel und der Erde', options: ['حُكْمُ', 'مُلْكُ', 'دِينُ'], correct: 1 },
            { arabic: 'مَن \u00a6 كُمْ', hint: '... wer vor euch war', options: ['قَبْلِ', 'إِلَىٰ', 'فِي'], correct: 0 },
            { arabic: 'وَإِلٰهُكُمْ إِلٰهٌ \u00a6', hint: 'Und euer Anbetungswürdiger ist ein einziger Anbetungswürdiger', options: ['عَظِيمٌ', 'جَمِيعًا', 'وَٰحِدٌ'], correct: 2 },
            { arabic: 'فِي ٱلْأُولَىٰ وَ\u00a6', hint: 'Im Diesseits und im Jenseits', options: ['ٱلْآخِرَةِ', 'ٱلْأَرْضِ', 'ٱلَّيْلِ'], correct: 0 },
            { arabic: '\u00a6 خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ', hint: 'Wer erschuf die Himmel und die Erde?', options: ['مَنْ', 'مَا', 'أَنْ'], correct: 0 },
            { arabic: 'وَهُوَ ٱلَّذِي \u00a6 كُم', hint: 'Und Er ist derjenige, Der euch erschuf', options: ['خَلَقَ', 'يَهْدِي', 'يَشَاءُ'], correct: 0 },
            { arabic: 'إِنَّ ٱللَّهَ عَلَىٰ كُلِّ شَيْءٍ \u00a6', hint: 'Gewiss, Allah ist über jede Sache allmächtig', options: ['عَلِيمٌ', 'قَدِيرٌ', 'خَبِيرٌ'], correct: 1 }
        ]
    }
};